from .blog import router
from .category import router
from .menu import router
from .admin import router
from .pricing import router
from .slide import router
from .cat_product import router
from .product import router
from .social_media import router
from .management import router